name: "Podcast Generator"
author: "Dundi"
description: "Generates a feed for a podcast from a YAML file"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "git-branch"
  color: "red"

inputs:
  email:
    description: "The committer's email address"
    required: false
    default: "github-actions@github.com"

  name:
    description: "The committer's name"
    required: false
    default: "github-actions"
